# Generated by cucumber-sinatra. (2015-03-14 16:54:54 +0000)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'app/till.rb')

require 'capybara'
require 'capybara/rspec'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = Till

class TillWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  TillWorld.new
end
